// Label key diselaraskan dengan kelas dari dataset publik:
// - TrashNet (glass, paper, cardboard, plastic, metal, trash)
// - RealWaste (cardboard, food_organics, glass, metal, paper, plastic, textile, vegetation)
// - Garbage Classification v2 (metal, glass, biological, paper, battery, cardboard, shoes, clothes, plastic)
//
// Nanti kalau backend YOLO return label, tinggal lookup ke sini.
// bbox: koordinat normalized 0–1 { x1, y1, x2, y2 } — diganti response API YOLO nanti.

const TRASH_DATA = {

  // ── PLASTIC ────────────────────────────────────────────────────────────
  plastic: {
    label: "Plastik",
    code: "PLT-01",
    category: "Anorganik",
    confidence: 94.3,
    decompose: "20–500 tahun",
    bin: "Kuning",
    binHex: "#F59E0B",
    tip: "Cek kode daur ulang di bawah kemasan (segitiga angka 1–7). Bersihkan dari sisa makanan sebelum dibuang ke bank sampah.",
    icon: "🧴",
    bbox: { x1: 0.28, y1: 0.10, x2: 0.72, y2: 0.90 },
  },
  plastic_bag: {
    label: "Kantong Plastik",
    code: "PLT-02",
    category: "Anorganik",
    confidence: 88.7,
    decompose: "10–20 tahun",
    bin: "Kuning",
    binHex: "#F59E0B",
    tip: "Kantong plastik tipis sulit didaur ulang secara konvensional. Gunakan tas belanja kain yang bisa dipakai ulang.",
    icon: "🛍️",
    bbox: { x1: 0.15, y1: 0.20, x2: 0.85, y2: 0.80 },
  },
  plastic_bottle: {
    label: "Botol Plastik",
    code: "PLT-03",
    category: "Anorganik",
    confidence: 96.8,
    decompose: "450 tahun",
    bin: "Kuning",
    binHex: "#F59E0B",
    tip: "Botol PET (kode 1) sangat mudah didaur ulang menjadi serat kain atau botol baru. Lepas tutup dan label sebelum dibuang.",
    icon: "🍶",
    bbox: { x1: 0.30, y1: 0.08, x2: 0.70, y2: 0.92 },
  },

  // ── PAPER ──────────────────────────────────────────────────────────────
  paper: {
    label: "Kertas",
    code: "KTS-01",
    category: "Anorganik",
    confidence: 93.5,
    decompose: "2–6 minggu",
    bin: "Kuning",
    binHex: "#F59E0B",
    tip: "Kertas kering bisa didaur ulang. Hindari kertas berminyak, thermal (struk), atau berlaminasi — tidak bisa didaur ulang.",
    icon: "📄",
    bbox: { x1: 0.12, y1: 0.18, x2: 0.88, y2: 0.82 },
  },
  cardboard: {
    label: "Kardus",
    code: "KTS-02",
    category: "Anorganik",
    confidence: 95.2,
    decompose: "2 bulan",
    bin: "Kuning",
    binHex: "#F59E0B",
    tip: "Lipat kardus agar hemat tempat. Lepaskan selotip, staples, dan lapisan plastik sebelum disetor ke bank sampah.",
    icon: "📦",
    bbox: { x1: 0.08, y1: 0.15, x2: 0.92, y2: 0.85 },
  },

  // ── GLASS ──────────────────────────────────────────────────────────────
  glass: {
    label: "Kaca / Botol Kaca",
    code: "KCA-01",
    category: "Anorganik",
    confidence: 91.4,
    decompose: "1 juta tahun",
    bin: "Kuning",
    binHex: "#F59E0B",
    tip: "Kaca dapat didaur ulang tanpa batas tanpa kehilangan kualitas. Bersihkan dan setor ke bank sampah terdekat.",
    icon: "🍾",
    bbox: { x1: 0.28, y1: 0.08, x2: 0.72, y2: 0.92 },
  },
  broken_glass: {
    label: "Kaca Pecah",
    code: "KCA-02",
    category: "Anorganik",
    confidence: 86.1,
    decompose: "1 juta tahun",
    bin: "Kuning",
    binHex: "#F59E0B",
    tip: "HATI-HATI! Bungkus dengan beberapa lapis koran atau kardus sebelum dibuang agar tidak melukai petugas.",
    icon: "🪟",
    bbox: { x1: 0.10, y1: 0.15, x2: 0.90, y2: 0.85 },
  },

  // ── METAL ──────────────────────────────────────────────────────────────
  metal: {
    label: "Logam / Kaleng",
    code: "LGM-01",
    category: "Anorganik",
    confidence: 94.6,
    decompose: "50–200 tahun",
    bin: "Kuning",
    binHex: "#F59E0B",
    tip: "Kaleng aluminium adalah material daur ulang paling efisien — hemat 95% energi dibanding produksi baru. Cuci sebelum dibuang.",
    icon: "🥫",
    bbox: { x1: 0.28, y1: 0.12, x2: 0.72, y2: 0.88 },
  },
  metal_scrap: {
    label: "Besi / Logam Bekas",
    code: "LGM-02",
    category: "Anorganik",
    confidence: 88.9,
    decompose: "100+ tahun",
    bin: "Kuning",
    binHex: "#F59E0B",
    tip: "Logam bekas bisa dijual ke pengepul besi tua atau disetor ke bank sampah. Jangan dicampur dengan sampah organik.",
    icon: "🔩",
    bbox: { x1: 0.15, y1: 0.30, x2: 0.85, y2: 0.70 },
  },

  // ── BIOLOGICAL / FOOD ORGANICS ─────────────────────────────────────────
  biological: {
    label: "Sampah Organik",
    code: "ORG-01",
    category: "Organik",
    confidence: 90.3,
    decompose: "2–4 minggu",
    bin: "Hijau",
    binHex: "#10B981",
    tip: "Pisahkan dari sampah kering. Bisa diolah menjadi kompos rumahan — kurangi volume sampah hingga 60%.",
    icon: "🍱",
    bbox: { x1: 0.18, y1: 0.20, x2: 0.82, y2: 0.80 },
  },
  food_organics: {
    label: "Sisa Makanan",
    code: "ORG-02",
    category: "Organik",
    confidence: 87.5,
    decompose: "1–4 minggu",
    bin: "Hijau",
    binHex: "#10B981",
    tip: "Sisa nasi, sayur, dan buah sangat baik untuk kompos. Hindari membuang ke saluran air karena menyebabkan penyumbatan.",
    icon: "🍚",
    bbox: { x1: 0.20, y1: 0.22, x2: 0.80, y2: 0.78 },
  },
  vegetation: {
    label: "Sampah Hijau / Tanaman",
    code: "ORG-03",
    category: "Organik",
    confidence: 92.1,
    decompose: "1–3 bulan",
    bin: "Hijau",
    binHex: "#10B981",
    tip: "Daun kering dan ranting kecil sangat baik sebagai bahan kompos atau mulsa. Jangan dibakar — polusi udara berbahaya.",
    icon: "🍂",
    bbox: { x1: 0.05, y1: 0.10, x2: 0.95, y2: 0.90 },
  },

  // ── TEXTILE ────────────────────────────────────────────────────────────
  textile: {
    label: "Tekstil / Pakaian",
    code: "TKS-01",
    category: "Anorganik",
    confidence: 83.7,
    decompose: "1–5 tahun",
    bin: "Kuning",
    binHex: "#F59E0B",
    tip: "Pakaian layak pakai: donasikan. Tidak layak: jadikan kain lap atau setor ke bank tekstil untuk didaur ulang.",
    icon: "👕",
    bbox: { x1: 0.10, y1: 0.18, x2: 0.90, y2: 0.82 },
  },
  shoes: {
    label: "Sepatu Bekas",
    code: "TKS-02",
    category: "Anorganik",
    confidence: 85.2,
    decompose: "25–40 tahun",
    bin: "Kuning",
    binHex: "#F59E0B",
    tip: "Sepatu masih layak bisa didonasikan. Yang rusak bisa dibawa ke program daur ulang sepatu dari brand tertentu.",
    icon: "👟",
    bbox: { x1: 0.15, y1: 0.25, x2: 0.85, y2: 0.75 },
  },

  // ── BATTERY / B3 ───────────────────────────────────────────────────────
  battery: {
    label: "Baterai",
    code: "B3-01",
    category: "B3",
    confidence: 97.1,
    decompose: "Tidak terurai",
    bin: "Drop Box B3",
    binHex: "#EF4444",
    tip: "JANGAN buang ke tempat sampah biasa! Mengandung merkuri dan kadmium. Setor ke drop box B3 di Indomaret/Alfamart.",
    icon: "🔋",
    bbox: { x1: 0.25, y1: 0.25, x2: 0.75, y2: 0.75 },
  },
  electronics: {
    label: "Elektronik Bekas",
    code: "B3-02",
    category: "B3",
    confidence: 94.8,
    decompose: "Tidak terurai",
    bin: "Drop Box B3",
    binHex: "#EF4444",
    tip: "E-waste mengandung logam berat berbahaya. Serahkan ke program take-back produsen atau gerai resmi (iBox, Samsung Store, dll).",
    icon: "📱",
    bbox: { x1: 0.28, y1: 0.12, x2: 0.72, y2: 0.88 },
  },
  lightbulb: {
    label: "Lampu Bekas",
    code: "B3-03",
    category: "B3",
    confidence: 91.3,
    decompose: "Tidak terurai",
    bin: "Drop Box B3",
    binHex: "#EF4444",
    tip: "Lampu neon/CFL mengandung merkuri. Jangan dihancurkan! Bawa utuh ke fasilitas pengumpulan limbah B3.",
    icon: "💡",
    bbox: { x1: 0.25, y1: 0.10, x2: 0.75, y2: 0.90 },
  },

  // ── MISCELLANEOUS TRASH ────────────────────────────────────────────────
  trash: {
    label: "Sampah Campur",
    code: "MSC-01",
    category: "Anorganik",
    confidence: 78.4,
    decompose: "Bervariasi",
    bin: "Hitam",
    binHex: "#6B7280",
    tip: "Sampah residu yang tidak bisa didaur ulang. Usahakan kurangi dari sumber — pilih produk dengan kemasan minimal.",
    icon: "🗑️",
    bbox: { x1: 0.12, y1: 0.18, x2: 0.88, y2: 0.82 },
  },
  cigarette: {
    label: "Puntung Rokok",
    code: "MSC-02",
    category: "B3",
    confidence: 89.6,
    decompose: "10–15 tahun",
    bin: "Hitam",
    binHex: "#6B7280",
    tip: "Puntung rokok mengandung ribuan bahan kimia berbahaya. Jangan dibuang sembarangan — bisa mencemari air tanah.",
    icon: "🚬",
    bbox: { x1: 0.30, y1: 0.35, x2: 0.70, y2: 0.65 },
  },
};

export default TRASH_DATA;